name: Python workflow
on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '1 * * * 4' # run every hour
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone gemini-pro-bot repo
        run: |
          git clone https://github.com/hrishikeshp7/gemini-pro-bot
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get secrets
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "BOT_TOKEN is $BOT_TOKEN"
          echo "GOOGLE_API_KEY is $GOOGLE_API_KEY"
      - name: Run main.py
        run: |
          python main.py
